### ISSUE TITLE
add README to analysis_pipeline/testdata

### ISSUE THREAD

**Issue by smgogarten** [UW-GAC/topmed_workshop_2018#10]
Describe source of 1000 genomes data and note it is build 37 / hg19.

**Comment by bheavner** [comment]
FYI - I'm planning to use freeze 5 data for the annotation-based aggregation section, which is build 38, but I don't think that will really matter apart from potential confusion for participants. I'll make the example files for them to work with, but so it shouldn't be a problem apart from perhaps needing to coordinate a bit with you to make sure I'm giving you reasonable input files for association testing.
